import React from 'react'
import { useTranslate } from 'react-polyglot';
import Collateral from './components/Collateral';
import Psm from './components/Psm';
import Pip from './components/Pip'
import CollateralChart from './components/CollateralChart';
import Clip from './components/Clip';
import Vest from './components/Vest';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';
import { useLocation, useHistory } from "react-router-dom";
import { configs } from "./config"
const { ETHERSCAN_URL, CHAINLOG_URL } = configs
const formatAmount = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 0,
  maximumFractionDigits: 2
})

const formatNoDecimals = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0
})

const formatCurrency = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 2,
  maximumFractionDigits: 4
})

const formatTwoDp = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

const formatPercent = new Intl.NumberFormat('en-US', {
  style: 'percent',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

const formatFiveDp = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 5,
  maximumFractionDigits: 5
})

const formatSixDp = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 6,
  maximumFractionDigits: 6
})

const formatEightDp = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 8,
  maximumFractionDigits: 8
})

const Main = (props) => {
  const t = useTranslate()
  document.title = `${formatNoDecimals.format(props.debt)} - GSUc Stats`
  const sysCollat = props.sysLocked / props.debt

  const nextFlap = () =>
    formatAmount.format(
      (Number(props.surplusBuffer)
        + Number(props.surplusBump))
      - Number(props.sysSurplus)
    )

  // hack till Main component is broken into component per section
  const location = useLocation();
  const history = useHistory();
  const indexToTab = ['/overview', '/collateral', '/oracles', '/auctions', '/ecosystem', '/addresses', '/vesting']
  function tabNameToIndex() {
    let i = indexToTab.indexOf(location.pathname)
    return (i >= 0 ? i : 0)
  }

  return (
    <div>
      <div className="container">
        <Tabs defaultIndex={tabNameToIndex()} onSelect={index => history.push(indexToTab[index])}>
          <TabList style={{ color: 'white' }}>
            <Tab><p className="is-size-5">Overview</p></Tab>
            <Tab><p className="is-size-5">Collateral</p></Tab>
            <Tab><p className="is-size-5">Oracles</p></Tab>
            <Tab><p className="is-size-5">Auctions</p></Tab>
            <Tab><p className="is-size-5">Ecosystem</p></Tab>
            <Tab><p className="is-size-5">Addresses</p></Tab>
            {/* <Tab><p className="is-size-5">Vesting</p></Tab> */}
          </TabList>

          <TabPanel>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.debt}>
                    {props.debt >= 420000000 && props.debt < 421000000 && <span role="img" aria-label="Tree">🌲</span>} {formatAmount.format(props.debt)} / {formatAmount.format(props.Line)}
                  </h3>
                  <h4 className="subtitle is-size-3">{t('daistats.total_token', { token: 'GSUc' })}</h4>
                  {/* <HistoricalDebtChart data={props.historicalDebt} /> */}
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <CollateralChart ilks={props.ilks} debt={props.sysLocked} useValue={true} />
                  <h4 className="subtitle is-size-4">GSUc Collateralization</h4>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <CollateralChart ilks={props.ilks} debt={props.debt} groupBy={true} />
                  <h4 className="subtitle is-size-4">GSUc Generated by Collateral</h4>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.sysLocked}>${formatAmount.format(props.sysLocked)}</h3>
                  <h4 className="subtitle is-size-4">{t('daistats.total_locked')}</h4>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={sysCollat}>{formatPercent.format(sysCollat)}</h3>
                  <h4 className="title subtitle is-size-4">{t('daistats.collat_ratio')}</h4>
                </div>
              </div>
            </div>
          </TabPanel>
          <TabPanel>
            <Tabs>
              <TabList>
                <Tab><p className="is-size-5">ERC-20</p></Tab>
                <Tab><p className="is-size-5">ERC-20 LP</p></Tab>
                <Tab><p className="is-size-5">Real World Assets</p></Tab>
                <Tab><p className="is-size-5">Peg Stability Modules</p></Tab>
                <Tab><p className="is-size-5">Direct Deposits</p></Tab>
                <Tab><p className="is-size-5">Deprecated</p></Tab>
              </TabList>

              <TabPanel>
                <Collateral {...props} ilk="ETH-A" supply={props.ethSupply} />
                <Collateral {...props} ilk="ETH-B" supply={props.ethSupply} />
                <Collateral {...props} ilk="ETH-C" supply={props.ethSupply} />
                <Collateral {...props} ilk="WBTC-A" />
                <Collateral {...props} ilk="WBTC-B" />
                <Collateral {...props} ilk="WBTC-C" />
              </TabPanel>
              <TabPanel>
                {/* <Collateral {...props} ilk="UNIV2USDCETH-A" showLockedDecimals={true} />
        <Collateral {...props} ilk="UNIV2DAIUSDC-A" showLockedDecimals={true} />
        <Collateral {...props} ilk="GUNIV3DAIUSDC1-A" />
        <Collateral {...props} ilk="GUNIV3DAIUSDC2-A" />
        <Collateral {...props} ilk="CRVV1ETHSTETH-A" showLockedDecimals={true} /> */}
              </TabPanel>
              <TabPanel>
                {/* <Collateral {...props} ilk="RWA001-A" />
        <Collateral {...props} ilk="RWA002-A" />
        <Collateral {...props} ilk="RWA003-A" />
        <Collateral {...props} ilk="RWA004-A" />
        <Collateral {...props} ilk="RWA005-A" />
        <Collateral {...props} ilk="RWA006-A" />
        <Collateral {...props} ilk="RWA008-A" />
        <Collateral {...props} ilk="RWA009-A" /> */}
              </TabPanel>
              <TabPanel>
                {/* <Psm {...props} ilk="PSM-USDC-A" />
        <Psm {...props} ilk="PSM-USDP-A" />
        <Psm {...props} ilk="PSM-GUSD-A" /> */}
              </TabPanel>
              <TabPanel>
                {/* <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiTargetSupply}>{formatAmount.format(props.d3mAdaiTargetSupply)}</h3>
              <h4 className="title subtitle is-size-4">aDAI Target Supply</h4>
              <h6 className="subtitle is-size-6" title={props.d3mAdaiAdjustment}>Adjustment: {formatAmount.format(props.d3mAdaiAdjustment)}</h6>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiAvailableLiquidity}>{formatAmount.format(props.d3mAdaiAvailableLiquidity)}</h3>
              <h4 className="title subtitle is-size-4">Available Liquidity</h4>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiTotalSupply}>{formatAmount.format(props.d3mAdaiTotalSupply)}</h3>
              <h4 className="title subtitle is-size-4">aDAI Total Supply</h4>
              <h6 className="title subtitle is-size-6">Variable Debt: {formatAmount.format(props.d3mAdaiTotalSupplyVariable)}</h6>
              <h6 className="title subtitle is-size-6">Stable Debt: {formatAmount.format(props.d3mAdaiTotalSupplyFixed)}</h6>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiBar}>{formatPercent.format(props.d3mAdaiBar)}</h3>
              <h4 className="title subtitle is-size-4">aDAI Target Interest Rate</h4>
              <h6 className="title subtitle is-size-6" title={props.d3mAdaiFeesPending}>Fees Pending: {formatAmount.format(props.d3mAdaiFeesPending)}</h6>
              <h6 className="title subtitle is-size-6" title={props.d3mAdaiIncentive}>Incentive Balance: {formatAmount.format(props.d3mAdaiIncentive)} stkAAVE</h6>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiDepositAPR}>{formatPercent.format(props.d3mAdaiDepositAPR)}</h3>
              <h4 className="title subtitle is-size-4">Deposit Rate (APR)</h4>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiVariableBorrowAPR}>{formatPercent.format(props.d3mAdaiVariableBorrowAPR)}</h3>
              <h4 className="title subtitle is-size-4">Variable Borrow Rate (APR)</h4>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.d3mAdaiStableBorrowAPR}>{formatPercent.format(props.d3mAdaiStableBorrowAPR)}</h3>
              <h4 className="title subtitle is-size-4">Stable Borrow Rate (APR)</h4>
            </div>
          </div>
        </div>
        <Collateral {...props} ilk="DIRECT-AAVEV2-DAI" /> */}
              </TabPanel>
              <TabPanel>
                {/* <Collateral {...props} ilk="AAVE-A" />
        <Collateral {...props} ilk="BAL-A" />
        <Collateral {...props} ilk="BAT-A" />
        <Collateral {...props} ilk="COMP-A" />
        <Collateral {...props} ilk="KNC-A" />
        <Collateral {...props} ilk="LRC-A" />
        <Collateral {...props} ilk="TUSD-A" />
        <Collateral {...props} ilk="UNI-A" />
        <Collateral {...props} ilk="UNIV2AAVEETH-A" showLockedDecimals={true} />
        <Collateral {...props} ilk="UNIV2DAIETH-A" />
        <Collateral {...props} ilk="UNIV2LINKETH-A" />
        <Collateral {...props} ilk="UNIV2UNIETH-A" />
        <Collateral {...props} ilk="UNIV2WBTCDAI-A" showLockedDecimals={true} />
        <Collateral {...props} ilk="UNIV2WBTCETH-A" showLockedDecimals={true} />
        <Collateral {...props} ilk="USDC-B" />
        <Collateral {...props} ilk="USDT-A" />
        <Collateral {...props} ilk="ZRX-A" /> */}
              </TabPanel>
            </Tabs>
          </TabPanel>
          <TabPanel>
            <div className="columns">
              <Pip {...props} token="ETH" ilk="ETH-A" formater={formatTwoDp} />
              {/* <Pip {...props} token="wstETH" ilk="WSTETH-A" formater={formatTwoDp} /> */}
              <Pip {...props} token="BTC" ilk="WBTC-A" formater={formatTwoDp} />
            </div>
            {/* <div className="columns">
          <Pip {...props} token="LINK" ilk="LINK-A" formater={formatTwoDp} />
          <Pip {...props} token="MANA" ilk="MANA-A" formater={formatCurrency} />
          <Pip {...props} token="MATIC" ilk="MATIC-A" formater={formatCurrency} />
        </div>
        <div className="columns">
          <Pip {...props} token="YFI" ilk="YFI-A" formater={formatTwoDp} />
          <Pip {...props} token="USDC, TUSD, USDP, GUSD, aDAI" ilk="USDC-A" formater={formatCurrency}/>
        </div>
        <div className="columns">
        </div>
        <div className="columns">
          <Pip {...props} token="UniV2UsdcEth" ilk="UNIV2USDCETH-A" formater={formatNoDecimals} />
          <Pip {...props} token="UniV2DaiUsdc" ilk="UNIV2DAIUSDC-A" formater={formatNoDecimals} />
        </div>
        <div className="columns">
          <Pip {...props} token="GUniV3DaiUsdc1" ilk="GUNIV3DAIUSDC1-A" formater={formatTwoDp} />
          <Pip {...props} token="GUniV3DaiUsdc2" ilk="GUNIV3DAIUSDC2-A" formater={formatFiveDp} />
          <Pip {...props} token="CrvV1EthSteth" ilk="CRVV1ETHSTETH-A" formater={formatTwoDp} />
        </div> */}

            {/* <div className="column">
              <div className="box has-text-centered">
                <h3 className="title" title={props.mkrPrice}>${formatCurrency.format(props.mkrPrice)}</h3>
                <p className="title subtitle is-size-4">MKR Price</p>
              </div>
            </div> */}

          </TabPanel>
          <TabPanel>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.flapKicks}>{formatAmount.format(props.flapKicks)}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.dai_surplus_auctions')}</p>
                  <p className="subtitle is-size-6">{t('daistats.till_next_flap')}: {nextFlap()}</p>
                  <p className="title subtitle is-size-6">Beg: {formatPercent.format(props.flapBeg - 1)} Ttl: {props.flapTtl / 60}m Tau: {props.flapTau / 60 / 60}h</p>
                  <p className="title subtitle is-size-6" title={props.surplusBump}>{t('daistats.lot')}: {formatAmount.format(props.surplusBump)} Lid: {formatAmount.format(props.flapLid)}</p>
                  <p className="title subtitle is-size-6" title={props.flapFill}>Fill: {formatAmount.format(props.flapFill)}</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.cdps}>{props.cdps}</h3>
                  <p className="subtitle is-size-4">{t('daistats.vaults_opened')}</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.mkrSupply}>{formatAmount.format(props.mkrSupply)}</h3>
                  <p className="subtitle is-size-4">{t('daistats.token_supply', { token: 'GSUc' })}</p>
                  <a href={`${ETHERSCAN_URL}/address/${props.MCD_PAUSE_PROXY}`} target="_blank" rel="noopener noreferrer">
                    <p className="subtitle is-size-6" title={props.protocolTreasury}>
                      Protocol Treasury: {formatAmount.format(props.protocolTreasury)} GSUc
                    </p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.flopKicks}>{formatAmount.format(props.flopKicks)}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.debt_flop_auctions')}</p>
                  <p className="title subtitle is-size-6">{t('daistats.initial_lot_size')}: {formatAmount.format(props.debtDump)} GSUc</p>
                  <p className="title subtitle is-size-6">{t('daistats.initial_price')}: ${formatAmount.format(props.debtSize / props.debtDump)}</p>
                  <p className="title subtitle is-size-6">Beg: {formatPercent.format(props.flopBeg - 1)} Pad: {formatPercent.format(props.flopPad - 1)}</p>
                  <p className="title subtitle is-size-6">Ttl: {props.flopTtl / 60}m Tau: {props.flopTau / 60 / 60}h</p>
                  <p className="title subtitle is-size-6">Flop delay: {props.flopDelay / 60 / 60}h</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={Math.min(props.vow_dai, props.sysDebt)}>{formatAmount.format(Math.min(props.vow_dai, props.sysDebt))}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.debt_available_heal')}</p>
                  <p className="title subtitle is-size-6">{t('daistats.debt_buffer')}: {formatAmount.format(props.debtSize)}</p>
                  {/*<p className="title subtitle is-size-6" title={props.vice}>Total Unbacked Dai (vice): {formatAmount.format(props.vice)}</p>*/}
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.sysSurplus}>{formatAmount.format(props.sysSurplus)}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.system_surplus')}</p>
                  <p className="title subtitle is-size-6" title={props.surplusBuffer}>{t('daistats.surplus_buffer')}: {formatAmount.format(props.surplusBuffer)}</p>
                  <p className="title subtitle is-size-4">Hump Lerp</p>
                  <p className="title subtitle is-size-6" title={props.lerpHumpStart}>Start: {formatNoDecimals.format(props.lerpHumpStart)}</p>
                  <p className="title subtitle is-size-6" title={props.lerpHumpCurrent}>Value: {formatNoDecimals.format(props.lerpHumpCurrent)}</p>
                  <p className="title subtitle is-size-6" title={props.lerpHumpEnd}>End: {formatNoDecimals.format(props.lerpHumpEnd)}</p>
                  <p className="title subtitle is-size-6" title={props.lerpHumpStartTime}>Start Date: {props.lerpHumpStartTime}</p>
                  <p className="title subtitle is-size-6" title={props.lerpHumpDuration}>Duration: {formatAmount.format(props.lerpHumpDuration / 86400)} Days</p>
                  <p className="title subtitle is-size-6" title={props.lerpHumpAdjustment}>Pending Change: {formatNoDecimals.format(props.lerpHumpAdjustment)}</p>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.dirt}>{formatAmount.format(props.dirt)}</h3>
                  <p className="title subtitle is-size-4" title="Aggregate Dai collection target of all active auctions across all collateral types">{/*t('daistats.Dirt')*/}Total Unbacked Dai including Penalties (Dirt)</p>
                  <p className="subtitle is-size-6" title={props.hole}>t('daistats.Hole')Global Limit (Hole) {formatAmount.format(props.hole)}</p>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column table-container">
                <table className="table is-narrow" style={{ backgroundColor: '#192734', color: '#e6e8f1' }}>
                  <Clip heading={true} />
                  <tbody>
                    <Clip {...props} token="ETH-A" ilk="ETH-A" />
                    <Clip {...props} token="ETH-B" ilk="ETH-B" />
                    <Clip {...props} token="ETH-C" ilk="ETH-C" />
                    <Clip {...props} token="WBTC-A" ilk="WBTC-A" />
                    <Clip {...props} token="WBTC-B" ilk="WBTC-B" />
                    <Clip {...props} token="WBTC-C" ilk="WBTC-C" />
                  </tbody>
                </table>
              </div>
            </div>
          </TabPanel>
          <TabPanel>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.pauseDelay}>{props.pauseDelay / 60 / 60}h</h3>
                  <p className="title subtitle is-size-4">{/*t('daistats.gsm_pause_delay')*/}GSM Pause Delay</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.flashLine}>{formatAmount.format(props.flashLine)}</h3>
                  <p className="title subtitle is-size-4">{/*t('daistats.flash_loan_limit')*/}GSUc Flash Loan Limit</p>
                  <p className="subtitle is-size-6">{/*t('daistats.fee')}*/}Fee: 0.00%</p>
                  <p className="title subtitle is-size-6" title={props.flashLegacyLine}>Legacy Limit: {formatAmount.format(props.flashLegacyLine)}</p>
                  <p className="title subtitle is-size-6">{/*t('daistats.fee')}*/}Legacy Fee: {formatPercent.format(props.flashLegacyToll)}</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.esmMin}>{formatAmount.format(props.esmMin)}</h3>
                  <p className="title subtitle is-size-4">{/*t('daistats.esm_threshold')*/}ESM Threshold</p>
                  <p className="subtitle is-size-6" title={props.esmSum}>{/*t('daistats.total_MKR_burned')}*/}Total GSUc Burned: {formatSixDp.format(props.esmSum)}</p>
                  <p className="title subtitle is-size-6" title={props.endWait}>{/*t('daistats.end_wait')}*/}ESM Delay: {props.endWait / 60 / 60}h</p>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.daiSupply}>
                    {formatAmount.format(props.daiSupply)}
                  </h3>
                  <p className="subtitle is-size-4">{
                    t('daistats.token_supply', { token: 'GSUc (ERC20)' })} ({formatAmount.format(props.daiSupply / props.debt * 100)}%)
                  </p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.savingsDai}>{formatAmount.format(props.savingsDai)}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.dai_in_dsr')}
                    ({formatAmount.format(props.savingsDai / props.debt * 100)}%)</p>
                  <p className="subtitle is-size-6">({t('daistats.pie_in_dsr')}: {formatAmount.format(props.savingsPie)})</p>
                </div>
              </div>

              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.potFee}>{formatPercent.format(props.potFee)}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.dai_savings_rate')}</p>
                  <p className="subtitle is-size-6">{t('daistats.last_drip')}: {props.potDrip}</p>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.optimisticDaiSupply}>{formatAmount.format(props.optimisticDaiSupply)}</h3>
                  <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'GSUc', dex: 'Optimism' })}</p>
                  <p className="title subtitle is-size-6">
                    <a href="https://gateway.optimism.io/" target="_blank" rel="noopener noreferrer">
                      Optimism Gateway
                    </a>
                  </p>
                  {/*<p className="subtitle is-size-6">{t('daistats.token_in_dex', { token: 'ETH', dex: 'Optimism' })}: {formatAmount.format(props.optimisticEthSupply)}</p> */}
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.starknetDaiSupply}>{formatAmount.format(props.starknetDaiSupply)}</h3>
                  <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'GSUc', dex: 'Starknet' })}</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.balancerV2Dai}>{formatAmount.format(props.balancerV2Dai)}</h3>
                  <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'GSUc', dex: 'Balancer V2' })}</p>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.chaiSupply}>{formatAmount.format(props.chaiSupply)}</h3>
                  <p className="title subtitle is-size-4">{t('daistats.token_supply', { token: 'Chai' })} <span role="img" aria-label="chai">🍵</span></p>
                  <p className="subtitle is-size-6">({t('daistats.dai_brewing')}: {formatAmount.format(props.daiBrewing)})</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.oasisDexDai}>{formatAmount.format(props.oasisDexDai)}</h3>
                  <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'GSUc', dex: 'Oasis Dex' })}</p>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.uniswapDai}>{formatAmount.format(props.uniswapDai)}</h3>
                  <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'GSUc', dex: 'Uniswap V2 (GSUc/ETH)' })}</p>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title" title={props.bkrSupply}>{formatAmount.format(props.bkrSupply)}</h3>
                  <p className="title subtitle is-size-4">
                    <a href={`${ETHERSCAN_URL}/token/${props.BKR}`} target="_blank" rel="noopener noreferrer">
                      {t('daistats.token_supply', { token: 'Breaker (BKR)' })}
                    </a>
                  </p>
                  <p className="title subtitle is-size-6" title={props.mkrBroken}>GSUp Broken: {formatEightDp.format(props.mkrBroken)}</p>
                  <p className="title subtitle is-size-6">
                    <a href="https://makerbreak.io/" target="_blank" rel="noopener noreferrer">Convert GSUp to BKR with Makerbreak.io</a>
                  </p>
                </div>
              </div>
            </div>
          </TabPanel>
          <TabPanel>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.GOV_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> GovAlpha</h3>
                    <p className="subtitle is-size-7">{props.GOV_MULTISIG}</p>
                  </a>
                  <a href={`${ETHERSCAN_URL}/address/${props.GOV_MULTISIG_2}`} target="_blank" rel="noopener noreferrer">
                    <p className="subtitle is-size-7">{props.GOV_MULTISIG_2}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.RISK_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Risk Core Unit</h3>
                    <p className="subtitle is-size-7">{props.RISK_MULTISIG}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.GRO_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Growth Core Unit</h3>
                    <p className="subtitle is-size-7">{props.GRO_MULTISIG}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.IN_WALLET}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Data Insights Core Unit</h3>
                    <p className="subtitle is-size-7">{props.IN_WALLET}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.COM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Governance Communications Core Unit</h3>
                    <p className="subtitle is-size-7">{props.COM_MULTISIG}</p>
                  </a>
                  <a href={`${ETHERSCAN_URL}/address/${props.COM_ER_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <p className="subtitle is-size-7">{props.COM_ER_MULTISIG}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.RWF_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Real World Core Unit</h3>
                    <p className="subtitle is-size-7">{props.RWF_MULTISIG}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.CP_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Content Production Unit</h3>
                    <p className="subtitle is-size-7">{props.CP_MULTISIG}</p>
                  </a>
                  <a href={`${ETHERSCAN_URL}/address/${props.CP_MULTISIG_2}`} target="_blank" rel="noopener noreferrer">
                    <p className="subtitle is-size-7">{props.CP_MULTISIG_2}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.SES_AUDITORS_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Sustainable Ecosystem Scaling Core Unit (SES)</h3>
                    <p className="subtitle is-size-7">{props.SES_AUDITORS_MULTISIG}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.SES_PERMANENT_TEAM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> SES Permanent Team</h3>
                    <p className="subtitle is-size-7">{props.SES_PERMANENT_TEAM_MULTISIG}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.SES_PERMANENT_TEAM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> SES Incubation Program</h3>
                    <p className="subtitle is-size-7">{props.SES_INCUBATION_PROGRAM_MULTISIG}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.SES_PERMANENT_TEAM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> SES Grants Program</h3>
                    <p className="subtitle is-size-7">{props.SES_GRANTS_PROGRAM_MULTISIG}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.SNE_WALLET}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> StarkNet Engineering Core Unit</h3>
                    <p className="subtitle is-size-7">{props.SNE_WALLET}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.SH_WALLET}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Strategic Happiness Core Unit</h3>
                    <p className="subtitle is-size-7">{props.SH_WALLET}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.PE_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Protocol Engineering Core Unit</h3>
                    <p className="subtitle is-size-7">{props.PE_MULTISIG}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.ORA_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Oracle Core Unit</h3>
                    <p className="subtitle is-size-7">{props.ORA_MULTISIG}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.ORA_ER_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Oracle Emergency Fund</h3>
                    <p className="subtitle is-size-7">{props.ORA_ER_MULTISIG}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.DAIF_WALLET}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Dai Foundation Core Unit</h3>
                    <p className="subtitle is-size-7">{props.DAIF_WALLET}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.DAIF_EF_WALLET}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Dai Foundation Emergency Fund</h3>
                    <p className="subtitle is-size-7">{props.DAIF_EF_WALLET}</p>
                  </a>
                </div>
              </div>
            </div>
            <hr />
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/address/${props.hat}#code`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Hat</h3>
                    <p className="subtitle is-size-7">{props.hat}</p>
                  </a>
                </div>
              </div>
            </div>
            <hr />
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  {/* <a href="https://tokenlists.org/token-list?url=https://daistats.com/makerdao.tokenlist.json" target="_blank" rel="noopener noreferrer">
                    <h3 className="title">MakerDAO Tokenlist v0.7.1</h3>
                  </a> */}
                  <a href="/makerdao.tokenlist.json" target="_blank" rel="noopener noreferrer">
                    <p className="subtitle is-size-7">{`gsuprotocol.tokenlist.json`}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={CHAINLOG_URL} target="_blank" rel="noopener noreferrer">
                    <h3 className="title">Multi-Collateral GSUc Public Releases</h3>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/token/${props.MCD_DAI}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> GSUc</h3>
                    <p className="subtitle is-size-7">{props.MCD_DAI}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/token/${props.MCD_GOV}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> GSUp</h3>
                    <p className="subtitle is-size-7">{props.MCD_GOV}</p>
                  </a>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/token/${props.ETH}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> WETH</h3>
                    <p className="subtitle is-size-7">{props.ETH}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`${ETHERSCAN_URL}/token/${props.WBTC}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> WBTC</h3>
                    <p className="subtitle is-size-7">{props.WBTC}</p>
                  </a>
                </div>
              </div>
            </div>

            <hr />
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`https://optimistic.etherscan.io/token/${props.OPTIMISTIC_DAI}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Optimistic GSUc</h3>
                    <p className="subtitle is-size-7">{props.OPTIMISTIC_DAI}</p>
                  </a>
                </div>
              </div>
              <div className="column">
                <div className="box has-text-centered">
                  <a href={`https://optimistic.etherscan.io/token/${props.OPTIMISTIC_MKR}`} target="_blank" rel="noopener noreferrer">
                    <h3 className="title"><i className="fal fa-file-code"></i> Optimistic GSUp</h3>
                    <p className="subtitle is-size-7">{props.OPTIMISTIC_MKR}</p>
                  </a>
                </div>
              </div>
            </div>
          </TabPanel>
          {/* <TabPanel>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title">GSUc</h3>
                  <table className="table" style={{ margin: '0 auto', backgroundColor: '#192734', color: '#e6e8f1' }}>
                    <Vest heading={true} />
                    <tbody>
                      {props.vestingDaiLegacy.map((award, idx) => (
                        <Vest key={award.usr + award.bgn} award={award} />
                      ))}
                      <tr><td colspan="10">&nbsp;</td></tr>
                      {props.vestingDai.map((award, idx) => (
                        <Vest key={award.usr + award.bgn} award={award} />
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div className="columns">
              <div className="column">
                <div className="box has-text-centered">
                  <h3 className="title">GSUp</h3>
                  <table className="table" style={{ margin: '0 auto', backgroundColor: '#192734', color: '#e6e8f1' }}>
                    <Vest heading={true} />
                    <tbody>
                      {props.vestingMkrTreasury.map((award, idx) => (
                        <Vest key={award.usr + award.bgn} award={award} />
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </TabPanel> */}
        </Tabs>
      </div>
    </div>
  )
}

export default Main
