import React from 'react'
import { useTranslate } from 'react-polyglot';
import Collateral from './components/Collateral';
import HistoricalDebtChart from './components/HistoricalDebtChart';
import Pip from './components/Pip'
import CollateralChart from './components/CollateralChart';
import Clip from './components/Clip';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';
import { useLocation, useHistory } from "react-router-dom";


const formatAmount = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 0,
  maximumFractionDigits: 2
})

const formatForWBTC = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 0,
  maximumFractionDigits: 4
})

const formatNoDecimals = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0
})

const formatCurrency = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 2,
  maximumFractionDigits: 4
})

const formatTwoDp = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

const formatPercent = new Intl.NumberFormat('en-US', {
  style: 'percent',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
})

const formatPercentFee = new Intl.NumberFormat('en-US', {
  style: 'percent',
  minimumFractionDigits: 2,
  maximumFractionDigits: 4
})

const formatEightDp = new Intl.NumberFormat('en-US', {
  style: 'decimal',
  minimumFractionDigits: 8,
  maximumFractionDigits: 8
})

const Main = (props) => {
  const t = useTranslate()
  document.title = `${formatNoDecimals.format(props.debt)} - Dai Stats`
  const sysCollat = props.sysLocked / props.debt

  const nextFlap = () =>
    formatAmount.format(
      (Number(props.surplusBuffer)
        + Number(props.surplusBump))
      - Number(props.sysSurplus)
    )

  // hack till Main component is broken into component per section
  const location = useLocation();
  const history = useHistory();
  const indexToTab = ['/overview', '/collateral', '/oracles', '/auctions', '/ecosystem', '/addresses']
  function tabNameToIndex() {
    let i = indexToTab.indexOf(location.pathname)
    return (i >= 0 ? i : 0)
  }

  return (
    <div>
      <div className="container">
        <Tabs defaultIndex={tabNameToIndex()} onSelect={index => history.push(indexToTab[index])}>
          <TabList>
            <Tab><p className="is-size-5">Overview</p></Tab>
            <Tab><p className="is-size-5">Collateral</p></Tab>
            <Tab><p className="is-size-5">Oracles</p></Tab>
            <Tab><p className="is-size-5">Auctions</p></Tab>
            <Tab><p className="is-size-5">Ecosystem</p></Tab>
            <Tab><p className="is-size-5">Addresses</p></Tab>
          </TabList>

          <TabPanel>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.debt}>
                {props.debt >= 420000000 && props.debt < 421000000 && <span>🌲</span>} {formatAmount.format(props.debt)} / {formatAmount.format(props.Line)}
              </h3>
              <h4 className="subtitle is-size-3">{t('daistats.total_token', { token: 'Dai' })}</h4>
              <HistoricalDebtChart data={props.historicalDebt} />
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.sysLocked}>{formatAmount.format(props.sysLocked)}</h3>
              <h4 className="subtitle is-size-4">{t('daistats.total_locked')}</h4>
            </div>
          </div>
          {/*<div className="column">
            FIXME add Collateral Backing Dai chart
            <div className="box has-text-centered">
              <h3 className="title" title={sysCollat}>{formatPercent.format(sysCollat)}</h3>
              <h4 className="title subtitle is-size-4">{t('daistats.collat_ratio')}</h4>
            </div>
          </div>*/}
          <div className="column">
            <div className="box has-text-centered">
              <CollateralChart ilks={props.ilks} debt={props.debt} />
              <h4 className="subtitle is-size-4">Dai Generated by Collateral</h4>
            </div>
          </div>
        </div>
          </TabPanel>
          <TabPanel>
        <div>
          <div className="columns">
          <div className="column is-half">
            <div className="has-text-centered">
              <h3 className="title"
                title={props.psmUsdcALocked}>
                {formatAmount.format(props.psmUsdcALocked)} / {formatAmount.format(props.psmUsdcALine)}
              </h3>
              <p className="title subtitle is-size-4">
                {t('daistats.dai_from_token', { token: 'PSM-USDC-A' })} ({formatAmount.format(props.psmUsdcALocked / props.debt * 100)}%)
              </p>
              {props.ilks[34].lineMax > 0 && <p className="title subtitle is-size-6">{t('maker.debt_ceiling')}: {formatAmount.format(props.ilks[34].lineMax)}</p>}
              {props.ilks[34].lineMax > 0 && <p className="title subtitle is-size-6">Gap: {formatAmount.format(props.ilks[34].gap)} Ttl: {props.ilks[34].ttl / 60 / 60}h</p>}
              {props.ilks[34].lineMax > 0 && <p className="title subtitle is-size-6">Last Change: {props.ilks[34].lastInc}</p>}
              <p className="subtitle is-size-6">
                {t('daistats.utilization')}: {formatAmount.format(props.psmUsdcALocked / props.psmUsdcALine * 100)}%
              </p>
              <p className="subtitle is-size-6">
                <a href="https://ipfs.io/ipfs/QmY9WUjD3YYfyzmegDYxE8yZFcNT3L9TRQSGCJQaWjXxwk/" target="_blank" rel="noopener noreferrer">
                  Trade DAI & USDC with no price impact using the PSM
                </a>
              </p>
            </div>
          </div>
          <div className="column">
            <div className="has-text-centered">
              <h3 className="title" title={props.psmUsdcTin}>{formatPercentFee.format(props.psmUsdcTin)}</h3>
              <p className="title subtitle is-size-4">Fee in</p>
              <h3 className="title" title={props.psmUsdcTout}>{formatPercentFee.format(props.psmUsdcTout)}</h3>
              <p className="title subtitle is-size-4">Fee out</p>
            </div>
          </div>
          <div className="column">
            <div className="has-text-centered">
              <h3 className="title" title={props.psmUsdcALocked}>{formatNoDecimals.format(props.psmUsdcALocked)}</h3>
              <p className="title subtitle is-size-4">
                {t('daistats.token_locked', { token: 'USDC' })}
              </p>
              <p className="subtitle is-size-6">
                {t('daistats.token_supply_locked', { token: 'USDC' })}: {formatPercent.format(props.psmUsdcALocked / props.usdcSupply)}</p>
            </div>
          </div>
        </div>
        <hr />
        </div>
        <Collateral {...props} idx="0" fee={props.ethFee} />
        <Collateral {...props} idx="14" fee={props.ethBFee} />
        <Collateral {...props} idx="31" fee={props.ethCFee} />
        <Collateral {...props} idx="1" fee={props.batFee} />
        <Collateral {...props} idx="2" fee={props.usdcFee} />
        <Collateral {...props} idx="4" fee={props.usdcBFee} />
        <Collateral {...props} idx="3" fee={props.wbtcFee} />
        <Collateral {...props} idx="5" fee={props.tusdFee} />
        <Collateral {...props} idx="6" fee={props.kncAFee} />
        <Collateral {...props} idx="7" fee={props.zrxAFee} />
        <Collateral {...props} idx="8" fee={props.manaAFee} />
        <Collateral {...props} idx="9" fee={props.paxAFee} />
        <Collateral {...props} idx="10" fee={props.usdtAFee} />
        <Collateral {...props} idx="11" fee={props.compAFee} />
        <Collateral {...props} idx="12" fee={props.lrcAFee} />
        <Collateral {...props} idx="13" fee={props.linkAFee} />
        <Collateral {...props} idx="15" fee={props.balAFee} />
        <Collateral {...props} idx="16" fee={props.yfiAFee} />
        <Collateral {...props} idx="17" fee={props.gusdAFee} />
        <Collateral {...props} idx="18" fee={props.uniAFee} />
        <Collateral {...props} idx="19" fee={props.renbtcAFee} />
        <Collateral {...props} idx="20" fee={props.aaveAFee} />
        <Collateral {...props} idx="21" fee={props.univ2daiethAFee} />
        <Collateral {...props} idx="22" fee={props.univ2wbtcethAFee} showLockedDecimals={true} />
        <Collateral {...props} idx="23" fee={props.univ2usdcethAFee} showLockedDecimals={true} />
        <Collateral {...props} idx="24" fee={props.univ2daiusdcAFee} showLockedDecimals={true} />
        <Collateral {...props} idx="25" fee={props.univ2ethusdtAFee} showLockedDecimals={true} />
        <Collateral {...props} idx="26" fee={props.univ2linkethAFee} />
        <Collateral {...props} idx="27" fee={props.univ2uniethAFee} />
        <Collateral {...props} idx="28" fee={props.univ2wbtcdaiAFee} showLockedDecimals={true} />
        <Collateral {...props} idx="29" fee={props.univ2aaveethAFee} />
        <Collateral {...props} idx="30" fee={props.univ2daiusdtAFee} />
        <Collateral {...props} idx="32" fee={props.rwa001AFee} />
        <Collateral {...props} idx="33" fee={props.rwa002AFee} />
          </TabPanel>
          <TabPanel>
        <div className="columns">
          <Pip token="ETH" price={props.ethPrice} priceNxt={props.ethPriceNxt} priceMedian={props.ethPriceMedian} formater={formatTwoDp} zzz={props.ethZzz}/>
          <Pip token="BTC" price={props.wbtcPrice} priceNxt={props.wbtcPriceNxt} priceMedian={props.wbtcPriceMedian} formater={formatTwoDp} zzz={props.wbtcZzz}/>
          <Pip token="YFI" price={props.yfiPrice} priceNxt={props.yfiPriceNxt} priceMedian={props.yfiPriceMedian} formater={formatTwoDp} zzz={props.yfiZzz}/>
          <Pip token="UNI" price={props.uniPrice} priceNxt={props.uniPriceNxt} priceMedian={props.uniPriceMedian} formater={formatTwoDp} zzz={props.uniZzz}/>
        </div>
        <div className="columns">
          <Pip token="AAVE" price={props.aavePrice} priceNxt={props.aavePriceNxt} priceMedian={props.aavePriceMedian} formater={formatTwoDp} zzz={props.aaveZzz}/>
          <Pip token="BAL" price={props.balPrice} priceNxt={props.balPriceNxt} priceMedian={props.balPriceMedian} formater={formatTwoDp} zzz={props.balZzz}/>
          <Pip token="BAT" price={props.batPrice} priceNxt={props.batPriceNxt} priceMedian={props.batPriceMedian} formater={formatCurrency} zzz={props.batZzz}/>
          <Pip token="COMP" price={props.compPrice} priceNxt={props.compPriceNxt} priceMedian={props.compPriceMedian} formater={formatTwoDp} zzz={props.compZzz}/>
        </div>
        <div className="columns">
          <Pip token="KNC" price={props.kncPrice} priceNxt={props.kncPriceNxt} priceMedian={props.kncPriceMedian} formater={formatCurrency} zzz={props.kncZzz}/>
          <Pip token="LINK" price={props.linkPrice} priceNxt={props.linkPriceNxt} priceMedian={props.linkPriceMedian} formater={formatTwoDp} zzz={props.linkZzz}/>
          <Pip token="LRC" price={props.lrcPrice} priceNxt={props.lrcPriceNxt} priceMedian={props.lrcPriceMedian} formater={formatCurrency} zzz={props.lrcZzz}/>
          <Pip token="MANA" price={props.manaPrice} priceNxt={props.manaPriceNxt} priceMedian={props.manaPriceMedian} formater={formatCurrency} zzz={props.manaZzz}/>
        </div>
        <div className="columns">
          <Pip token="USDT" price={props.usdtPrice} priceNxt={props.usdtPriceNxt} priceMedian={props.usdtPriceMedian} formater={formatCurrency} zzz={props.usdtZzz}/>
          <Pip token="ZRX" price={props.zrxPrice} priceNxt={props.zrxPriceNxt} priceMedian={props.zrxPriceMedian} formater={formatCurrency} zzz={props.zrxZzz}/>
          <Pip token="USDC, TUSD, PAX, GUSD" price={props.tusdPrice} formater={formatCurrency}/>
          <Pip token="UniV2DaiEth" price={props.univ2daiethPrice} priceNxt={props.univ2daiethPriceNxt} formater={formatTwoDp} zzz={props.univ2daiethZzz}/>
        </div>
        <div className="columns">
          <Pip token="UniV2UniEth" price={props.univ2uniethPrice} priceNxt={props.univ2uniethPriceNxt} formater={formatTwoDp} zzz={props.univ2uniethZzz}/>
          <Pip token="UniV2WbtcEth" price={props.univ2wbtcethPrice} priceNxt={props.univ2wbtcethPriceNxt} formater={formatNoDecimals} zzz={props.univ2wbtcethZzz}/>
          <Pip token="UniV2UsdcEth" price={props.univ2usdcethPrice} priceNxt={props.univ2usdcethPriceNxt} formater={formatNoDecimals} zzz={props.univ2usdcethZzz}/>
        </div>
        <div className="columns">
          <Pip token="UniV2DaiUsdc" price={props.univ2daiusdcPrice} priceNxt={props.univ2daiusdcPriceNxt} formater={formatNoDecimals} zzz={props.univ2daiusdcZzz}/>
          <Pip token="UniV2EthUsdt" price={props.univ2ethusdtPrice} priceNxt={props.univ2ethusdtPriceNxt} formater={formatNoDecimals} zzz={props.univ2ethusdtZzz}/>
          <Pip token="UniV2LinkEth" price={props.univ2linkethPrice} priceNxt={props.univ2linkethPriceNxt} formater={formatTwoDp} zzz={props.univ2linkethZzz}/>
        </div>
        <div className="columns">
          <Pip token="UniV2WbtcDai" price={props.univ2wbtcdaiPrice} priceNxt={props.univ2wbtcdaiPriceNxt} formater={formatNoDecimals} zzz={props.univ2wbtcdaiZzz}/>
          <Pip token="UniV2AaveEth" price={props.univ2aaveethPrice} priceNxt={props.univ2aaveethPriceNxt} formater={formatTwoDp} zzz={props.univ2aaveethZzz}/>
          <Pip token="UniV2DaiUsdt" price={props.univ2daiusdtPrice} priceNxt={props.univ2daiusdtPriceNxt} formater={formatTwoDp} zzz={props.univ2daiusdtZzz}/>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.rwa001Price}>${formatTwoDp.format(props.rwa001Price)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.token_price', { token: 'RWA001' })}</p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.rwa002Price}>${formatTwoDp.format(props.rwa002Price)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.token_price', { token: 'RWA002' })}</p>
            </div>
          </div>
        </div>

          {/* <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={sysCollat}>{formatPercent.format(sysCollat)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.collat_ratio')}</p>
              <p className="subtitle is-size-6">{t('daistats.total_locked')}: ${formatAmount.format(props.sysLocked)}</p>
            </div>
          </div> */}

          {/* <div className="column">
              <div className="box has-text-centered">
                <h3 className="title" title={props.mkrPrice}>${formatCurrency.format(props.mkrPrice)}</h3>
                <p className="title subtitle is-size-4">MKR Price</p>
              </div>
            </div> */}

          </TabPanel>
          <TabPanel>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.flapKicks}>{formatAmount.format(props.flapKicks)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.dai_surplus_auctions')}</p>
              <p className="subtitle is-size-6">{t('daistats.till_next_flap')}: {nextFlap()}</p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.cdps}>{props.cdps}</h3>
              <p className="subtitle is-size-4">{t('daistats.vaults_opened')}</p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.mkrSupply}>{formatAmount.format(props.mkrSupply)}</h3>
              <p className="subtitle is-size-4">{t('daistats.token_supply', { token: 'MKR' })}</p>
              <a href={`https://etherscan.io/address/${props.MCD_PAUSE_PROXY}`} target="_blank" rel="noopener noreferrer">
                <p className="subtitle is-size-6" title={props.protocolTreasury}>
                  Protocol Treasury: {formatAmount.format(props.protocolTreasury)} MKR
                </p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.flopKicks}>{formatAmount.format(props.flopKicks)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.debt_flop_auctions')}</p>
              <p className="subtitle is-size-6">
                {t('daistats.initial_lot_size')}: {formatAmount.format(props.debtDump)} MKR {t('daistats.initial_price')}: ${formatAmount.format(props.debtSize / props.debtDump)}
              </p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={Math.min(props.vow_dai, props.sysDebt)}>{formatAmount.format(Math.min(props.vow_dai, props.sysDebt))}</h3>
              <p className="title subtitle is-size-4">{t('daistats.debt_available_heal')}</p>
              <p className="subtitle is-size-6">{t('daistats.debt_buffer')}: {formatAmount.format(props.debtSize)}</p>
              {/* <p className="subtitle is-size-6">vice: {formatAmount.format(props.vice)}</p> */}
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.sysSurplus}>{formatAmount.format(props.sysSurplus)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.system_surplus')}</p>
              <p className="subtitle is-size-6" title={props.surplusBuffer}>{t('daistats.surplus_buffer')}: {formatAmount.format(props.surplusBuffer)} / {t('daistats.lot')}: {formatAmount.format(props.surplusBump)}</p>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.dirt}>{formatAmount.format(props.dirt)}</h3>
              <p className="title subtitle is-size-4">{/*t('daistats.Dirt')*/}Total Bad Debt including Penalties (Dirt)</p>
              <p className="subtitle is-size-6">{/*t('daistats.Hole')*/}Global Limit (Hole) {formatAmount.format(props.hole)}</p>
            </div>
          </div>
        </div>
        <div className="columns">
          <Clip {...props} token="ETH-A" idx="0"/>
          <Clip {...props} token="ETH-B" idx="14"/>
          <Clip {...props} token="ETH-C" idx="31"/>
          <Clip {...props} token="WBTC" idx="3"/>
          <Clip {...props} token="KNC" idx="6"/>
        </div>
        <div className="columns">
          <Clip {...props} token="ZRX" idx="7"/>
          <Clip {...props} token="MANA" idx="8"/>
          <Clip {...props} token="USDT" idx="10"/>
          <Clip {...props} token="COMP" idx="11"/>
          <Clip {...props} token="LRC" idx="12"/>
        </div>
        <div className="columns">
          <Clip {...props} token="LINK" idx="13"/>
          <Clip {...props} token="BAL" idx="15"/>
          <Clip {...props} token="YFI" idx="16"/>
          <Clip {...props} token="UNI" idx="18"/>
          <Clip {...props} token="RENBTC" idx="19"/>
        </div>
        <div className="columns">
          <Clip {...props} token="AAVE" idx="20"/>
          <Clip {...props} token="UniV2DaiEth" idx="21"/>
          <Clip {...props} token="UniV2WbtcEth" idx="22"/>
          <Clip {...props} token="UniV2UsdcEth" idx="23"/>
          <Clip {...props} token="UniV2DaiUsdc" idx="24"/>
        </div>
        <div className="columns">
          <Clip {...props} token="UniV2EthUsdt" idx="25"/>
          <Clip {...props} token="UniV2LinkEth" idx="26"/>
          <Clip {...props} token="UniV2UniEth" idx="27"/>
          <Clip {...props} token="UniV2WbtcDai" idx="28"/>
          <Clip {...props} token="UniV2AaveEth" idx="29"/>
        </div>
        <div className="columns">
          <Clip {...props} token="UniV2DaiUsdt" idx="30"/>
          <Clip {...props} token="BAT" idx="1"/>
          <Clip {...props} token="USDC-A" idx="2"/>
          <Clip {...props} token="USDC-B" idx="4"/>
        </div>
        <div className="columns">
          <Clip {...props} token="TUSD" idx="5"/>
          <Clip {...props} token="GUSD" idx="17"/>
          <Clip {...props} token="PAXUSD" idx="9"/>
          <Clip {...props} token="PSM-USDC-A" idx="34"/>
        </div>
          </TabPanel>
          <TabPanel>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.pauseDelay}>{props.pauseDelay / 60 / 60}h</h3>
              <p className="title subtitle is-size-4">{/*t('daistats.gsm_pause_delay')*/}GSM Pause Delay</p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.flashLine}>{formatAmount.format(props.flashLine)}</h3>
              <p className="title subtitle is-size-4">{/*t('daistats.flash_loan_limit')*/}Dai Flash Loan Limit</p>
              <p className="subtitle is-size-6">{/*t('daistats.fee')}*/}Fee: {formatPercent.format(props.flashToll)}</p>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.daiSupply}>
                {formatAmount.format(props.daiSupply)}
              </h3>
              <p className="subtitle is-size-4">{
                t('daistats.token_supply', { token: 'Dai (ERC20)' })} ({formatAmount.format(props.daiSupply / props.debt * 100)}%)
              </p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.savingsDai}>{formatAmount.format(props.savingsDai)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.dai_in_dsr')}
                  ({formatAmount.format(props.savingsDai / props.debt * 100)}%)</p>
              <p className="subtitle is-size-6">({t('daistats.pie_in_dsr')}: {formatAmount.format(props.savingsPie)})</p>
            </div>
          </div>

          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.potFee}>{props.potFee}%</h3>
              <p className="title subtitle is-size-4">{t('daistats.dai_savings_rate')}</p>
              <p className="subtitle is-size-6">{t('daistats.last_drip')}: {props.potDrip}</p>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.chaiSupply}>{formatAmount.format(props.chaiSupply)}</h3>
              <p className="title subtitle is-size-4">{t('daistats.token_supply', { token: 'Chai' })} <span role="img" aria-label="chai">🍵</span></p>
              <p className="subtitle is-size-6">({t('daistats.dai_brewing')}: {formatAmount.format(props.daiBrewing)})</p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.oasisDexDai}>{formatAmount.format(props.oasisDexDai)}</h3>
              <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'Dai', dex: 'Oasis Dex' })}</p>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.uniswapDai}>{formatAmount.format(props.uniswapDai)}</h3>
              <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'Dai', dex: 'Uniswap V2 (Dai/ETH)' })}</p>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.balancerV2Dai}>{formatAmount.format(props.balancerV2Dai)}</h3>
              <p className="subtitle is-size-4">{t('daistats.token_in_dex', { token: 'Dai', dex: 'Balancer V2' })}</p>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <h3 className="title" title={props.bkrSupply}>{formatAmount.format(props.bkrSupply)}</h3>
              <p className="title subtitle is-size-4">
                <a href={`https://etherscan.io/token/${props.BKR}`} target="_blank" rel="noopener noreferrer">
                  {t('daistats.token_supply', { token: 'Breaker (BKR)' })}
                </a>
              </p>
              <p className="title subtitle is-size-6" title={props.mkrBroken}>MKR Broken: {formatEightDp.format(props.mkrBroken)}</p>
              <p className="title subtitle is-size-6">
                <a href="https://makerbreak.io/" target="_blank" rel="noopener noreferrer">Convert MKR to BKR with Makerbreak.io</a>
              </p>
            </div>
          </div>
        </div>
          </TabPanel>
          <TabPanel>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.GOV_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> GovAlpha</h3>
                <p className="subtitle is-size-7">{props.GOV_MULTISIG}</p>
              </a>
              <a href={`https://etherscan.io/address/${props.GOV_MULTISIG_2}`} target="_blank" rel="noopener noreferrer">
                <p className="subtitle is-size-7">{props.GOV_MULTISIG_2}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.RISK_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Risk Core Unit</h3>
                <p className="subtitle is-size-7">{props.RISK_MULTISIG}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.GRO_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Growth Core Unit</h3>
                <p className="subtitle is-size-7">{props.GRO_MULTISIG}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.RWF_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Real World Core Unit</h3>
                <p className="subtitle is-size-7">{props.RWF_MULTISIG}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.CP_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Content Production Unit</h3>
                <p className="subtitle is-size-7">{props.CP_MULTISIG}</p>
              </a>
              <a href={`https://etherscan.io/address/${props.CP_MULTISIG_2}`} target="_blank" rel="noopener noreferrer">
                <p className="subtitle is-size-7">{props.CP_MULTISIG_2}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.SES_AUDITORS_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Sustainable Ecosystem Scaling Core Unit (SES)</h3>
                <p className="subtitle is-size-7">{props.SES_AUDITORS_MULTISIG}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.SES_PERMANENT_TEAM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> SES Permanent Team</h3>
                <p className="subtitle is-size-7">{props.SES_PERMANENT_TEAM_MULTISIG}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.SES_PERMANENT_TEAM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> SES Incubation Program</h3>
                <p className="subtitle is-size-7">{props.SES_INCUBATION_PROGRAM_MULTISIG}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.SES_PERMANENT_TEAM_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> SES Grants Program</h3>
                <p className="subtitle is-size-7">{props.SES_GRANTS_PROGRAM_MULTISIG}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.PE_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Protocol Engineering Core Unit</h3>
                <p className="subtitle is-size-7">{props.PE_MULTISIG}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.ORA_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Oracle Core Unit</h3>
                <p className="subtitle is-size-7">{props.ORA_MULTISIG}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.ORA_ER_MULTISIG}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Oracle Emergency Fund</h3>
                <p className="subtitle is-size-7">{props.ORA_ER_MULTISIG}</p>
              </a>
            </div>
          </div>
        </div>
        <hr />
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/address/${props.hat}#code`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Hat</h3>
                <p className="subtitle is-size-7">{props.hat}</p>
              </a>
            </div>
          </div>
        </div>
        <hr />
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.MCD_DAI}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> Dai</h3>
                <p className="subtitle is-size-7">{props.MCD_DAI}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.MCD_GOV}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> MKR</h3>
                <p className="subtitle is-size-7">{props.MCD_GOV}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.BAT}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> BAT</h3>
                <p className="subtitle is-size-7">{props.BAT}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.USDC}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> USDC</h3>
                <p className="subtitle is-size-7">{props.USDC}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.WBTC}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> WBTC</h3>
                <p className="subtitle is-size-7">{props.WBTC}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.AAVE}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> AAVE</h3>
                <p className="subtitle is-size-7">{props.AAVE}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.TUSD}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> TUSD</h3>
                <p className="subtitle is-size-7">{props.TUSD}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.KNC}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> KNC</h3>
                <p className="subtitle is-size-7">{props.KNC}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.ZRX}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> ZRX</h3>
                <p className="subtitle is-size-7">{props.ZRX}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.RENBTC}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> renBTC</h3>
                <p className="subtitle is-size-7">{props.RENBTC}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.MANA}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> MANA</h3>
                <p className="subtitle is-size-7">{props.MANA}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.PAXUSD}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> PAX</h3>
                <p className="subtitle is-size-7">{props.PAXUSD}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.USDT}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> USDT</h3>
                <p className="subtitle is-size-7">{props.USDT}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.COMP}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> COMP</h3>
                <p className="subtitle is-size-7">{props.COMP}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.LRC}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> LRC</h3>
                <p className="subtitle is-size-7">{props.LRC}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.LINK}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> LINK</h3>
                <p className="subtitle is-size-7">{props.LINK}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.BAL}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> BAL</h3>
                <p className="subtitle is-size-7">{props.BAL}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.YFI}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> YFI</h3>
                <p className="subtitle is-size-7">{props.YFI}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.GUSD}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> GUSD</h3>
                <p className="subtitle is-size-7">{props.GUSD}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNI}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UNI</h3>
                <p className="subtitle is-size-7">{props.UNI}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2DAIETH}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2DaiEth</h3>
                <p className="subtitle is-size-7">{props.UNIV2DAIETH}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2WBTCETH}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2WbtcEth</h3>
                <p className="subtitle is-size-7">{props.UNIV2WBTCETH}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2USDCETH}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2UsdcEth</h3>
                <p className="subtitle is-size-7">{props.UNIV2USDCETH}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2DAIUSDC}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2DaiUsdc</h3>
                <p className="subtitle is-size-7">{props.UNIV2DAIUSDC}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2ETHUSDT}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2EthUsdt</h3>
                <p className="subtitle is-size-7">{props.UNIV2ETHUSDT}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2LINKETH}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2LinkEth</h3>
                <p className="subtitle is-size-7">{props.UNIV2LINKETH}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2UNIETH}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2UniEth</h3>
                <p className="subtitle is-size-7">{props.UNIV2UNIETH}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2WBTCDAI}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2WbtcDai</h3>
                <p className="subtitle is-size-7">{props.UNIV2WBTCDAI}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2AAVEETH}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2AaveEth</h3>
                <p className="subtitle is-size-7">{props.UNIV2AAVEETH}</p>
              </a>
            </div>
          </div>
        </div>
        <div className="columns">
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.UNIV2DAIUSDT}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> UniV2DaiUsdt</h3>
                <p className="subtitle is-size-7">{props.UNIV2DAIUSDT}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.RWA001}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> RWA001</h3>
                <p className="subtitle is-size-7">{props.RWA001}</p>
              </a>
            </div>
          </div>
          <div className="column">
            <div className="box has-text-centered">
              <a href={`https://etherscan.io/token/${props.RWA002}`} target="_blank" rel="noopener noreferrer">
                <h3 className="title"><i className="fal fa-file-code"></i> RWA002</h3>
                <p className="subtitle is-size-7">{props.RWA002}</p>
              </a>
            </div>
          </div>
        </div>
          </TabPanel>
        </Tabs>
      </div>
    </div>
  )
}

export default Main
